[package]
name = "cplit"
version = "0.1.0"
authors = ["Leachim"]
keywords = ["competitive"]
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]

