[package]
name = "cplit"
version = "0.1.0"
authors = ["Licheam"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]

