[package]
name = "cplit"
version = "0.3.4"
authors = ["Leachim"]
keywords = ["competitive"]
description = "Competitive Programming Library in Rust"
license = "MIT"
repository = "https://github.com/Licheam/cplit"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]

